[package]
name = "policy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
paralegal-policy = { git = "https://github.com/brownsys/paralegal", rev = "c52fc5ccb2b9a14d307381b5567eb154b86667a9", version = "0.1.0" }
